django_easy_login/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^easy_login/', include('easy_login.urls', namespace='easy-login')),
    url(r'^test_app/', include('test_app.urls', namespace='test-app')),
]

easy_login/urls.py
from django.conf.urls import url

from easy_login.views import EasyLoginView

urlpatterns = [
    url('^easy_login_change/$',  EasyLoginView.as_view(), name='easy-login-change')
]

test_app/urls.py
from django.conf.urls import url

from test_app.views import ViewHome

urlpatterns = [
    url('^$',  ViewHome.as_view(), name='index')
]

test_app/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

easy_login/forms.py
from django import forms
from django.conf import settings
from django.contrib.auth import get_user_model

User = get_user_model()

view_settings = {
    'FILTER': {},
    'LIMIT': 10,
    'LABELS': [],
    'LOGIN_BY': 'both',
    'GET_BY': 'pk',
    'LOGIN_BUTTON': 'Login'
}

if hasattr(settings, 'EASY_LOGIN_SETTINGS'):
    view_settings.update(settings.EASY_LOGIN_SETTINGS)


class MyModelChoiceField(forms.ModelChoiceField):
    def label_from_instance(self, obj):
        """
        Updated function to show labels according to the settings
        """
        if view_settings['LABELS'] and type(view_settings['LABELS']) is list:
            labels = []
            for attr in view_settings['LABELS']:
                labels.append(str(getattr(obj, attr)))
            label = ', '.join(labels)
        elif callable(view_settings['LABELS']):
            label = view_settings['LABELS'](obj)
        else:
            label = obj
        return '{}'.format(label)


class EasyLoginForm(forms.Form):
    user_name = MyModelChoiceField(queryset=User.objects.none(), required=False)
    placeholder = 'ID' if view_settings['GET_BY'] == 'pk' else view_settings['GET_BY']
    user_id = forms.CharField(required=False, widget=forms.TextInput(attrs={'placeholder': placeholder}))
    login_by = view_settings['LOGIN_BY']
    login_button = view_settings['LOGIN_BUTTON']

    def __init__(self, *args, **kwargs):
        super(EasyLoginForm, self).__init__(*args, **kwargs)
        if args:
            self.fields['user_name'].queryset = User.objects.filter(**view_settings['FILTER'])
        else:
            self.fields['user_name'].queryset = User.objects.filter(**view_settings['FILTER'])[:view_settings['LIMIT']]

    def clean(self):
        """
        Validation if one from two params present in request.
        :return:
        """
        cleaned_data = super(EasyLoginForm, self).clean()
        user_name = cleaned_data.get("user_name")
        user_id = cleaned_data.get("user_id")

        if not any([user_name, user_id]):  # pragma: no cover
            raise forms.ValidationError("Please provide parameter user_name or user_id.")

easy_login/views.py
# -*- coding: utf-8 -*-
from django.urls import reverse
from django.conf import settings
from django.contrib.auth import login
from django.views.generic.base import View
from django.contrib.auth import get_user_model
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404

from easy_login.forms import EasyLoginForm, view_settings

User = get_user_model()


class EasyLoginView(View):
    """
    Easy login view for switch user without credentials
    """
    form_class = EasyLoginForm

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            user = form.cleaned_data['user_name']
            user_id = form.cleaned_data['user_id']
            get_by = {view_settings['GET_BY']: user_id}

            if user:
                login(request, user)
            elif user_id:
                obj_user = get_object_or_404(User, **get_by)
                login(request, obj_user)

        if hasattr(settings, 'EASY_URL_REDIRECT'):
            url = reverse(settings.EASY_URL_REDIRECT)

            return HttpResponseRedirect(url)

        return HttpResponseRedirect(self.request.META.get('HTTP_REFERER'))

test_app/views.py
# -*- coding: utf-8 -*-
from django.views.generic.base import TemplateView, View


class ViewHome(TemplateView):
    template_name = 'home.html'

easy_login/templates/easy_login_form.html
{% load i18n %}{% load static %}
<div id='easy_login' class="easy_login_bottom_left">
  <form method="post" action="{% url 'easy-login:easy-login-change' %}" id="easy_login_form">
      {% csrf_token %}
      <img onclick="EasyLogin.onImageClick()" alt="User" src="{% static 'easy_login/icons/user.svg' %}">
    <span id='easy_login_box' class='visible_box'>
        {%  if form.login_by == 'both' %}
            {{ form.user_name }}
            or by
            {{ form.user_id }}
        {% elif form.login_by == 'select' %}
            {{ form.user_name }}
        {% elif form.login_by == 'id' %}
            {{ form.user_id }}
        {% endif %}
        {% if form.login_by in 'both,id' %}
        <input type="submit" value="{{ form.login_button }}">
        {% endif %}
      <span id='current_user_information'>Current User: {{ current_user }} - ID: {{ current_user.id }}</span>
    </span>
  </form>
</div>

<link rel="stylesheet" href="{% static 'easy_login/css/main.css' %}" type="text/css" media="screen">
<script type="text/javascript" src="{% static 'easy_login/js/easy-login.js' %}"></script>

test_app/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>Test</h1>
{{ easy_login }}
</body>
</html>